### ISSUE TITLE
NX generate fails with Cannot find tsconfig.base.json

### ISSUE THREAD

**Issue by aczire** [betrueagency/nx-reactjs-elementor#7]
`
$ npx nx g @betrue/react-elementor:plugin oof-connector-elementor-react

>  NX  Generating @betrue/react-elementor:application

√ Which stylesheet format would you like to use? · styled-components
oof-connector-elementor-react-input
oof-connector-elementor-react-title,oof-connector-elementor-react-input

 >  NX   Cannot find tsconfig.base.json

`

Any idea how to fix this issue?

**Comment by alizarion** [comment]
Hi @aczire nx workspace create has been updated you have to choose 
integrated workspace with typescript configuration.
i have update the documentation too 

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Choose your style                     · integrated
✔ What to create in the new workspace   · ts
✔ Enable distributed caching to make your CI faster · No

**Comment by aczire** [comment]
Much appreciated. Seems good now.
